name: 'ecommerce_analytics'
version: '1.0.0'
config-version: 2

profile: 'ecommerce_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  #- "dbt_packages"

models:
  ecommerce_analytics:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts

# Temporarily remove vars and hooks to find the error
vars:
  start_date: '2023-01-01'
  end_date: '2024-12-31'

  # Reference date for recency calculations
  # In PROD: use current_timestamp()
  # In DEV: use end of data range to make demo realistic
  recency_reference_date: '2024-12-31'  
  
  # Default currency
  default_currency: 'EUR'